online_train:
  optimizer:
    name: sgd
    lr: 0.01
    weight_decay: 4e-5
    momentum: 0.9
    nesterov: True
  fg_weight: 10.0
  bg_weight: 1.0
  focal_gamma: 0.0
  training_strides: [8, 16, 32, 64]
  inference_stride: 1
  accuracy_threshold: 0.8
  max_updates: 16
  fine_classes: true
  sports_classes: false
  max_frames: 100000
  image_width: 1280
  image_height: 720
  image_mean: [0.43931922, 0.41310471, 0.37480941]
  image_std: [0.24272706, 0.23649098, 0.23429529]
  online_train: true
  scale_boxes: true
  video: null
  stats_path: 'stats'
  checkpoint_threshold: 100.
  resume_online: false
  ema: false
  ema_m: 0.99
  num_models: 1
  accuracy_lower_bound: 0.5
  warmup: 256
  model_avg_m: 0.9
  model_perf_win: 64
  freeze_enc: false
  freeze_dec: false
  cls_weight: [1,1,1,1]